name = "durable-scheduler-example"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-11-06"
main = "src/server/index.ts"

assets = { directory = "public" }


[[durable_objects.bindings]]
name = "SCHEDULER"
class_name = "Scheduler"

[[durable_objects.bindings]]
name = "TODOS"
class_name = "ToDos"


 [[migrations]]
tag = "v1"
new_sqlite_classes = [ "Scheduler", "ToDos" ]

[ai]
binding = "AI"
